name: utopia_cms_supabase
version: 0.1.0+3
resolution: workspace
description: Utopia CMS - Supabase
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ^3.11.0

dependencies:
  utopia_cms: ^0.2.1+1

  supabase_flutter: ^2.0.0
  fast_immutable_collections: ^11.1.0

