name: utopia_cms_firebase
version: 0.2.0+5
resolution: workspace
description: Utopia CMS - Firebase
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ^3.11.0
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^6.1.0
  utopia_cms:
  utopia_utils: ^0.3.3
